CREATE TABLE [serve].[ProjectPlanField] (
    [ProjectId]                   INT             NOT NULL,
    [PlanId]                      INT             NOT NULL,
    [CustomQuestionId]            INT             NOT NULL,
    [ProjectCustomQuestionFactId] INT             NULL,
    [CustomQuestionOptionId]      INT             NULL,
    [QuestionName]                NVARCHAR (4000) NOT NULL,
    [QuestionDisplayLabel]        NVARCHAR (4000) NULL,
    [QuestionDescription]         NVARCHAR (MAX)  NULL,
    [FieldType]                   NVARCHAR (100)  NULL,
    [QuestionSortOrder]           INT             NULL,
    [IsRequired]                  BIT             NOT NULL,
    [IsGrouping]                  BIT             NOT NULL,
    [IsMultiSelect]               BIT             NOT NULL,
    [MinValue]                    DECIMAL (18, 4) NULL,
    [MaxValue]                    DECIMAL (18, 4) NULL,
    [MaxLength]                   INT             NULL,
    [OptionCode]                  NVARCHAR (250)  NULL,
    [OptionValue]                 NVARCHAR (MAX)  NULL,
    [OptionLabel]                 NVARCHAR (MAX)  NULL,
    [ValueText]                   NVARCHAR (MAX)  NULL,
    [ValueNumber]                 DECIMAL (18, 4) NULL,
    [ValueBit]                    BIT             NULL,
    [ValueJson]                   NVARCHAR (MAX)  NULL,
    [AnswerText]                  NVARCHAR (MAX)  NULL,
    [AnswerNumber]                DECIMAL (18, 4) NULL,
    [AnswerBit]                   BIT             NULL,
    [AnswerJson]                  NVARCHAR (MAX)  NULL,
    [RulesJson]                   NVARCHAR (MAX)  NULL,
    [LabelJson]                   NVARCHAR (MAX)  NULL,
    [DefinitionJson]              NVARCHAR (MAX)  NULL,
    [DependencyJson]              NVARCHAR (MAX)  NULL,
    [VisibilityGroupId]           TINYINT         CONSTRAINT [DF_serve_ProjectPlanField_VisibilityGroupId] DEFAULT ((1)) NOT NULL,
    [RecordStatus]                VARCHAR (20)    CONSTRAINT [DF_serve_ProjectPlanField_RecordStatus] DEFAULT ('Active') NOT NULL,
    [CreatedAt]                   DATETIME2 (0)   NULL,
    [UpdatedAt]                   DATETIME2 (0)   NULL,
    [RefreshedAt]                 DATETIME2 (0)   CONSTRAINT [DF_serve_ProjectPlanField_RefreshedAt] DEFAULT (sysutcdatetime()) NOT NULL,
    CONSTRAINT [PK_serve_ProjectPlanField] PRIMARY KEY CLUSTERED ([ProjectId] ASC, [CustomQuestionId] ASC),
    CONSTRAINT [CK_serve_ProjectPlanField_RecordStatus] CHECK ([RecordStatus]='Deleted' OR [RecordStatus]='Inactive' OR [RecordStatus]='Active'),
    CONSTRAINT [FK_serve_ProjectPlanField_CustomQuestion] FOREIGN KEY ([CustomQuestionId]) REFERENCES [serve].[CustomQuestion] ([Id]),
    CONSTRAINT [FK_serve_ProjectPlanField_CustomQuestionOption] FOREIGN KEY ([CustomQuestionOptionId]) REFERENCES [serve].[CustomQuestionOption] ([Id]),
    CONSTRAINT [FK_serve_ProjectPlanField_Plan] FOREIGN KEY ([PlanId]) REFERENCES [serve].[Plan] ([Id]),
    CONSTRAINT [FK_serve_ProjectPlanField_Project] FOREIGN KEY ([ProjectId]) REFERENCES [serve].[Project] ([Id]),
    CONSTRAINT [FK_serve_ProjectPlanField_ProjectCustomQuestionFact] FOREIGN KEY ([ProjectCustomQuestionFactId]) REFERENCES [serve].[ProjectCustomQuestionFact] ([Id]),
    CONSTRAINT [FK_serve_ProjectPlanField_VisibilityGroup] FOREIGN KEY ([VisibilityGroupId]) REFERENCES [serve].[VisibilityGroup] ([Id])
);


GO

