-- Show Query Store plans, forcing state and retained runtime performance.
CREATE   VIEW [dba].[vw_Perf_QueryStorePlans]
AS
WITH RuntimeAggregated AS (SELECT rs.plan_id,SUM(CASE WHEN rs.execution_type=0 THEN rs.count_executions ELSE 0 END) AS SuccessfulExecutionCount,SUM(CASE WHEN rs.execution_type=3 THEN rs.count_executions ELSE 0 END) AS AbortedExecutionCount,SUM(CASE WHEN rs.execution_type=4 THEN rs.count_executions ELSE 0 END) AS ExceptionExecutionCount,MIN(rs.first_execution_time) AS FirstExecutionTime,MAX(rs.last_execution_time) AS LastExecutionTime,SUM(CASE WHEN rs.execution_type=0 THEN CONVERT(float,rs.avg_cpu_time)*rs.count_executions ELSE 0 END)/NULLIF(SUM(CASE WHEN rs.execution_type=0 THEN rs.count_executions ELSE 0 END),0)/1000.0 AS AvgCpuMs,SUM(CASE WHEN rs.execution_type=0 THEN CONVERT(float,rs.avg_duration)*rs.count_executions ELSE 0 END)/NULLIF(SUM(CASE WHEN rs.execution_type=0 THEN rs.count_executions ELSE 0 END),0)/1000.0 AS AvgDurationMs,SUM(CASE WHEN rs.execution_type=0 THEN CONVERT(float,rs.avg_logical_io_reads)*rs.count_executions ELSE 0 END)/NULLIF(SUM(CASE WHEN rs.execution_type=0 THEN rs.count_executions ELSE 0 END),0) AS AvgLogicalReads,MAX(CASE WHEN rs.execution_type=0 THEN rs.max_duration END)/1000.0 AS MaxDurationMs,MAX(CASE WHEN rs.execution_type=0 THEN rs.max_logical_io_reads END) AS MaxLogicalReads FROM sys.query_store_runtime_stats AS rs GROUP BY rs.plan_id)
SELECT p.query_id AS QueryId,p.plan_id AS PlanId,p.plan_group_id AS PlanGroupId,p.engine_version AS EngineVersion,p.compatibility_level AS CompatibilityLevel,p.query_plan_hash AS QueryPlanHash,p.is_trivial_plan AS IsTrivialPlan,p.is_parallel_plan AS IsParallelPlan,p.is_forced_plan AS IsForcedPlan,p.plan_forcing_type_desc AS PlanForcingType,p.force_failure_count AS ForceFailureCount,p.last_force_failure_reason_desc AS LastForceFailureReason,p.count_compiles AS CompileCount,p.initial_compile_start_time AS InitialCompileStartTime,p.last_compile_start_time AS LastCompileStartTime,p.last_execution_time AS PlanLastExecutionTime,CONVERT(decimal(18,2),p.avg_compile_duration/1000.0) AS AvgCompileDurationMs,CONVERT(decimal(18,2),p.last_compile_duration/1000.0) AS LastCompileDurationMs,p.plan_type_desc AS PlanType,ISNULL(ra.SuccessfulExecutionCount,0) AS SuccessfulExecutionCount,ISNULL(ra.AbortedExecutionCount,0) AS AbortedExecutionCount,ISNULL(ra.ExceptionExecutionCount,0) AS ExceptionExecutionCount,ra.FirstExecutionTime,ra.LastExecutionTime,CONVERT(decimal(18,2),ra.AvgCpuMs) AS AvgCpuMs,CONVERT(decimal(18,2),ra.AvgDurationMs) AS AvgDurationMs,CONVERT(decimal(18,2),ra.AvgLogicalReads) AS AvgLogicalReads,CONVERT(decimal(18,2),ra.MaxDurationMs) AS MaxDurationMs,ra.MaxLogicalReads,q.object_id AS ObjectId,ISNULL(OBJECT_SCHEMA_NAME(q.object_id),N'') AS ObjectSchemaName,ISNULL(OBJECT_NAME(q.object_id),N'') AS ObjectName,q.query_hash AS QueryHash,qt.query_sql_text AS QueryText,p.query_plan AS QueryPlan
FROM sys.query_store_plan AS p
INNER JOIN sys.query_store_query AS q ON q.query_id=p.query_id
INNER JOIN sys.query_store_query_text AS qt ON qt.query_text_id=q.query_text_id
LEFT JOIN RuntimeAggregated AS ra ON ra.plan_id=p.plan_id;

GO

