-- Show top Query Store queries across retained successful executions.
CREATE   VIEW [dba].[vw_Perf_QueryStoreTopQueries]
AS
WITH RuntimeAggregated AS (SELECT p.query_id,SUM(rs.count_executions) AS ExecutionCount,MIN(rs.first_execution_time) AS FirstExecutionTime,MAX(rs.last_execution_time) AS LastExecutionTime,SUM(CONVERT(float,rs.avg_cpu_time)*rs.count_executions)/1000.0 AS TotalCpuMs,SUM(CONVERT(float,rs.avg_cpu_time)*rs.count_executions)/NULLIF(SUM(rs.count_executions),0)/1000.0 AS AvgCpuMs,MAX(rs.max_cpu_time)/1000.0 AS MaxCpuMs,SUM(CONVERT(float,rs.avg_duration)*rs.count_executions)/1000.0 AS TotalDurationMs,SUM(CONVERT(float,rs.avg_duration)*rs.count_executions)/NULLIF(SUM(rs.count_executions),0)/1000.0 AS AvgDurationMs,MAX(rs.max_duration)/1000.0 AS MaxDurationMs,SUM(CONVERT(float,rs.avg_logical_io_reads)*rs.count_executions) AS TotalLogicalReads,SUM(CONVERT(float,rs.avg_logical_io_reads)*rs.count_executions)/NULLIF(SUM(rs.count_executions),0) AS AvgLogicalReads,MAX(rs.max_logical_io_reads) AS MaxLogicalReads,SUM(CONVERT(float,rs.avg_logical_io_writes)*rs.count_executions) AS TotalLogicalWrites,SUM(CONVERT(float,rs.avg_query_max_used_memory)*rs.count_executions)/NULLIF(SUM(rs.count_executions),0)*8.0/1024.0 AS AvgMemoryMB,MAX(rs.max_query_max_used_memory)*8.0/1024.0 AS MaxMemoryMB,SUM(CONVERT(float,rs.avg_tempdb_space_used)*rs.count_executions)/NULLIF(SUM(rs.count_executions),0)*8.0/1024.0 AS AvgTempdbMB,MAX(rs.max_tempdb_space_used)*8.0/1024.0 AS MaxTempdbMB,SUM(CONVERT(float,rs.avg_dop)*rs.count_executions)/NULLIF(SUM(rs.count_executions),0) AS AvgDegreeOfParallelism,MAX(rs.max_dop) AS MaxDegreeOfParallelism FROM sys.query_store_runtime_stats AS rs INNER JOIN sys.query_store_plan AS p ON p.plan_id=rs.plan_id WHERE rs.execution_type=0 GROUP BY p.query_id),PlanAggregated AS (SELECT query_id,COUNT_BIG(*) AS PlanCount,SUM(CASE WHEN is_forced_plan=1 THEN 1 ELSE 0 END) AS ForcedPlanCount FROM sys.query_store_plan GROUP BY query_id)
SELECT q.query_id AS QueryId,q.object_id AS ObjectId,ISNULL(OBJECT_SCHEMA_NAME(q.object_id),N'') AS ObjectSchemaName,ISNULL(OBJECT_NAME(q.object_id),N'') AS ObjectName,q.query_hash AS QueryHash,q.query_parameterization_type_desc AS QueryParameterizationType,pa.PlanCount,pa.ForcedPlanCount,ra.ExecutionCount,ra.FirstExecutionTime,ra.LastExecutionTime,CONVERT(decimal(20,2),ra.TotalCpuMs) AS TotalCpuMs,CONVERT(decimal(18,2),ra.AvgCpuMs) AS AvgCpuMs,CONVERT(decimal(18,2),ra.MaxCpuMs) AS MaxCpuMs,CONVERT(decimal(20,2),ra.TotalDurationMs) AS TotalDurationMs,CONVERT(decimal(18,2),ra.AvgDurationMs) AS AvgDurationMs,CONVERT(decimal(18,2),ra.MaxDurationMs) AS MaxDurationMs,CONVERT(decimal(18,2),ra.TotalCpuMs/NULLIF(ra.TotalDurationMs,0)) AS CpuToElapsedRatio,CONVERT(decimal(20,2),ra.TotalLogicalReads) AS TotalLogicalReads,CONVERT(decimal(18,2),ra.AvgLogicalReads) AS AvgLogicalReads,ra.MaxLogicalReads,CONVERT(decimal(20,2),ra.TotalLogicalWrites) AS TotalLogicalWrites,CONVERT(decimal(18,2),ra.AvgMemoryMB) AS AvgMemoryMB,CONVERT(decimal(18,2),ra.MaxMemoryMB) AS MaxMemoryMB,CONVERT(decimal(18,2),ra.AvgTempdbMB) AS AvgTempdbMB,CONVERT(decimal(18,2),ra.MaxTempdbMB) AS MaxTempdbMB,CONVERT(decimal(18,2),ra.AvgDegreeOfParallelism) AS AvgDegreeOfParallelism,ra.MaxDegreeOfParallelism,qt.query_sql_text AS QueryText
FROM RuntimeAggregated AS ra
INNER JOIN PlanAggregated AS pa ON pa.query_id=ra.query_id
INNER JOIN sys.query_store_query AS q ON q.query_id=ra.query_id
INNER JOIN sys.query_store_query_text AS qt ON qt.query_text_id=q.query_text_id;

GO

