-- Show parsed automatic tuning recommendations and observed impact.
CREATE   VIEW [dba].[vw_Perf_AutomaticTuningRecommendations]
AS
SELECT tr.name AS RecommendationName,tr.type AS RecommendationType,tr.reason AS RecommendationReason,tr.valid_since AS ValidSince,tr.last_refresh AS LastRefresh,tr.score AS Score,tr.is_executable_action AS IsExecutableAction,tr.is_revertable_action AS IsRevertableAction,tr.execute_action_start_time AS ExecuteActionStartTime,tr.execute_action_duration AS ExecuteActionDuration,tr.execute_action_initiated_by AS ExecuteActionInitiatedBy,tr.revert_action_start_time AS RevertActionStartTime,tr.revert_action_duration AS RevertActionDuration,tr.revert_action_initiated_by AS RevertActionInitiatedBy,st.CurrentValue AS CurrentState,st.StateReason,st.LastChangeText AS StateLastChange,st.ActionInitiatedBy AS StateActionInitiatedBy,d.QueryId,d.RegressedPlanId,d.RecommendedPlanId,d.RegressedPlanExecutionCount,d.RecommendedPlanExecutionCount,CONVERT(decimal(18,2),d.RegressedPlanCpuTimeAverage/1000.0) AS RegressedPlanAvgCpuMs,CONVERT(decimal(18,2),d.RecommendedPlanCpuTimeAverage/1000.0) AS RecommendedPlanAvgCpuMs,d.IndexName,d.IndexSchema,d.IndexTable,d.IndexColumns,d.IncludedColumns,d.IndexActionStartTime,d.IndexActionDuration,d.IndexActionRevertStartTime,d.IndexActionRevertDuration,d.ImplementationMethod,d.ImplementationScript,oi.VerificationProgressPercent,oi.SpaceChangeMB,oi.QueriesWithImprovedPerformance,oi.QueriesWithRegressedPerformance,oi.CpuChangeRelative,oi.LogicalReadsChangeRelative,oi.AffectedQueriesCpuChangeRelative,oi.AffectedQueriesLogicalReadsChangeRelative,tr.state AS RawStateJson,tr.details AS RawDetailsJson
FROM sys.dm_db_tuning_recommendations AS tr
OUTER APPLY OPENJSON(tr.state) WITH (CurrentValue nvarchar(60) '$.currentValue',StateReason nvarchar(4000) '$.reason',LastChangeText nvarchar(100) '$.lastChange',ActionInitiatedBy nvarchar(60) '$.actionInitiatedBy') AS st
OUTER APPLY OPENJSON(tr.details) WITH (QueryId bigint '$.planForceDetails.queryId',RegressedPlanId bigint '$.planForceDetails.regressedPlanId',RecommendedPlanId bigint '$.planForceDetails.recommendedPlanId',RegressedPlanExecutionCount bigint '$.planForceDetails.regressedPlanExecutionCount',RecommendedPlanExecutionCount bigint '$.planForceDetails.recommendedPlanExecutionCount',RegressedPlanCpuTimeAverage float '$.planForceDetails.regressedPlanCpuTimeAverage',RecommendedPlanCpuTimeAverage float '$.planForceDetails.recommendedPlanCpuTimeAverage',IndexName sysname '$.createIndexDetails.indexName',IndexSchema sysname '$.createIndexDetails.schema',IndexTable sysname '$.createIndexDetails.table',IndexColumns nvarchar(max) '$.createIndexDetails.indexColumns',IncludedColumns nvarchar(max) '$.createIndexDetails.includedColumns',IndexActionStartTime datetime2 '$.createIndexDetails.indexActionStartTime',IndexActionDuration nvarchar(100) '$.createIndexDetails.indexActionDuration',IndexActionRevertStartTime datetime2 '$.createIndexDetails.indexActionRevertStartTime',IndexActionRevertDuration nvarchar(100) '$.createIndexDetails.indexActionRevertDuration',ImplementationMethod nvarchar(100) '$.implementationDetails.method',ImplementationScript nvarchar(max) '$.implementationDetails.script') AS d
OUTER APPLY (SELECT MAX(CASE WHEN JSON_VALUE(j.value,'$.dimensionName')='VerificationProgress' THEN TRY_CONVERT(decimal(18,4),JSON_VALUE(j.value,'$.absoluteValue')) END) AS VerificationProgressPercent,MAX(CASE WHEN JSON_VALUE(j.value,'$.dimensionName')='SpaceChange' THEN TRY_CONVERT(decimal(18,4),JSON_VALUE(j.value,'$.absoluteValue')) END) AS SpaceChangeMB,MAX(CASE WHEN JSON_VALUE(j.value,'$.dimensionName')='QueriesWithImprovedPerformance' THEN TRY_CONVERT(decimal(18,4),JSON_VALUE(j.value,'$.absoluteValue')) END) AS QueriesWithImprovedPerformance,MAX(CASE WHEN JSON_VALUE(j.value,'$.dimensionName')='QueriesWithRegressedPerformance' THEN TRY_CONVERT(decimal(18,4),JSON_VALUE(j.value,'$.absoluteValue')) END) AS QueriesWithRegressedPerformance,MAX(CASE WHEN JSON_VALUE(j.value,'$.dimensionName')='CpuUtilization' THEN TRY_CONVERT(decimal(18,6),JSON_VALUE(j.value,'$.changeValueRelative')) END) AS CpuChangeRelative,MAX(CASE WHEN JSON_VALUE(j.value,'$.dimensionName')='LogicalReads' THEN TRY_CONVERT(decimal(18,6),JSON_VALUE(j.value,'$.changeValueRelative')) END) AS LogicalReadsChangeRelative,MAX(CASE WHEN JSON_VALUE(j.value,'$.dimensionName')='AffectedQueriesCpuUtilization' THEN TRY_CONVERT(decimal(18,6),JSON_VALUE(j.value,'$.changeValueRelative')) END) AS AffectedQueriesCpuChangeRelative,MAX(CASE WHEN JSON_VALUE(j.value,'$.dimensionName')='AffectedQueriesLogicalReads' THEN TRY_CONVERT(decimal(18,6),JSON_VALUE(j.value,'$.changeValueRelative')) END) AS AffectedQueriesLogicalReadsChangeRelative FROM OPENJSON(tr.details,'$.observedImpact') AS j) AS oi;

GO

