-- Show Query Store runtime metrics by query, plan, interval and execution type.
CREATE   VIEW [dba].[vw_Perf_QueryStoreRuntimeIntervals]
AS
WITH RuntimeAggregated AS (SELECT rs.plan_id,rs.runtime_stats_interval_id,rs.execution_type,rs.execution_type_desc,SUM(rs.count_executions) AS ExecutionCount,MIN(rs.first_execution_time) AS FirstExecutionTime,MAX(rs.last_execution_time) AS LastExecutionTime,SUM(CONVERT(float,rs.avg_cpu_time)*rs.count_executions)/1000.0 AS TotalCpuMs,SUM(CONVERT(float,rs.avg_cpu_time)*rs.count_executions)/NULLIF(SUM(rs.count_executions),0)/1000.0 AS AvgCpuMs,MIN(rs.min_cpu_time)/1000.0 AS MinCpuMs,MAX(rs.max_cpu_time)/1000.0 AS MaxCpuMs,SUM(CONVERT(float,rs.avg_duration)*rs.count_executions)/1000.0 AS TotalDurationMs,SUM(CONVERT(float,rs.avg_duration)*rs.count_executions)/NULLIF(SUM(rs.count_executions),0)/1000.0 AS AvgDurationMs,MIN(rs.min_duration)/1000.0 AS MinDurationMs,MAX(rs.max_duration)/1000.0 AS MaxDurationMs,SUM(CONVERT(float,rs.avg_logical_io_reads)*rs.count_executions) AS TotalLogicalReads,SUM(CONVERT(float,rs.avg_logical_io_reads)*rs.count_executions)/NULLIF(SUM(rs.count_executions),0) AS AvgLogicalReads,MAX(rs.max_logical_io_reads) AS MaxLogicalReads,SUM(CONVERT(float,rs.avg_logical_io_writes)*rs.count_executions) AS TotalLogicalWrites,SUM(CONVERT(float,rs.avg_logical_io_writes)*rs.count_executions)/NULLIF(SUM(rs.count_executions),0) AS AvgLogicalWrites,SUM(CONVERT(float,rs.avg_physical_io_reads)*rs.count_executions)/NULLIF(SUM(rs.count_executions),0) AS AvgPhysicalReads,SUM(CONVERT(float,rs.avg_dop)*rs.count_executions)/NULLIF(SUM(rs.count_executions),0) AS AvgDegreeOfParallelism,MAX(rs.max_dop) AS MaxDegreeOfParallelism,SUM(CONVERT(float,rs.avg_query_max_used_memory)*rs.count_executions)/NULLIF(SUM(rs.count_executions),0)*8.0/1024.0 AS AvgMemoryMB,MAX(rs.max_query_max_used_memory)*8.0/1024.0 AS MaxMemoryMB,SUM(CONVERT(float,rs.avg_tempdb_space_used)*rs.count_executions)/NULLIF(SUM(rs.count_executions),0)*8.0/1024.0 AS AvgTempdbMB,MAX(rs.max_tempdb_space_used)*8.0/1024.0 AS MaxTempdbMB,SUM(CONVERT(float,rs.avg_rowcount)*rs.count_executions)/NULLIF(SUM(rs.count_executions),0) AS AvgRowCount,MAX(rs.max_rowcount) AS MaxRowCount FROM sys.query_store_runtime_stats AS rs GROUP BY rs.plan_id,rs.runtime_stats_interval_id,rs.execution_type,rs.execution_type_desc)
SELECT p.query_id AS QueryId,ra.plan_id AS PlanId,ra.runtime_stats_interval_id AS RuntimeStatsIntervalId,rsi.start_time AS IntervalStartUtc,rsi.end_time AS IntervalEndUtc,q.object_id AS ObjectId,ISNULL(OBJECT_SCHEMA_NAME(q.object_id),N'') AS ObjectSchemaName,ISNULL(OBJECT_NAME(q.object_id),N'') AS ObjectName,q.query_hash AS QueryHash,p.query_plan_hash AS QueryPlanHash,q.query_parameterization_type_desc AS QueryParameterizationType,p.is_forced_plan AS IsForcedPlan,p.plan_forcing_type_desc AS PlanForcingType,p.is_parallel_plan AS IsParallelPlan,p.plan_type_desc AS PlanType,ra.execution_type AS ExecutionType,ra.execution_type_desc AS ExecutionTypeDescription,ra.ExecutionCount,ra.FirstExecutionTime,ra.LastExecutionTime,CONVERT(decimal(20,2),ra.TotalCpuMs) AS TotalCpuMs,CONVERT(decimal(18,2),ra.AvgCpuMs) AS AvgCpuMs,CONVERT(decimal(18,2),ra.MinCpuMs) AS MinCpuMs,CONVERT(decimal(18,2),ra.MaxCpuMs) AS MaxCpuMs,CONVERT(decimal(20,2),ra.TotalDurationMs) AS TotalDurationMs,CONVERT(decimal(18,2),ra.AvgDurationMs) AS AvgDurationMs,CONVERT(decimal(18,2),ra.MinDurationMs) AS MinDurationMs,CONVERT(decimal(18,2),ra.MaxDurationMs) AS MaxDurationMs,CONVERT(decimal(20,2),ra.TotalLogicalReads) AS TotalLogicalReads,CONVERT(decimal(18,2),ra.AvgLogicalReads) AS AvgLogicalReads,ra.MaxLogicalReads,CONVERT(decimal(20,2),ra.TotalLogicalWrites) AS TotalLogicalWrites,CONVERT(decimal(18,2),ra.AvgLogicalWrites) AS AvgLogicalWrites,CONVERT(decimal(18,2),ra.AvgPhysicalReads) AS AvgPhysicalReads,CONVERT(decimal(18,2),ra.AvgDegreeOfParallelism) AS AvgDegreeOfParallelism,ra.MaxDegreeOfParallelism,CONVERT(decimal(18,2),ra.AvgMemoryMB) AS AvgMemoryMB,CONVERT(decimal(18,2),ra.MaxMemoryMB) AS MaxMemoryMB,CONVERT(decimal(18,2),ra.AvgTempdbMB) AS AvgTempdbMB,CONVERT(decimal(18,2),ra.MaxTempdbMB) AS MaxTempdbMB,CONVERT(decimal(18,2),ra.AvgRowCount) AS AvgRowCount,ra.MaxRowCount,qt.query_sql_text AS QueryText
FROM RuntimeAggregated AS ra
INNER JOIN sys.query_store_runtime_stats_interval AS rsi ON rsi.runtime_stats_interval_id=ra.runtime_stats_interval_id
INNER JOIN sys.query_store_plan AS p ON p.plan_id=ra.plan_id
INNER JOIN sys.query_store_query AS q ON q.query_id=p.query_id
INNER JOIN sys.query_store_query_text AS qt ON qt.query_text_id=q.query_text_id;

GO

